# Nome do fluxo de trabalho.
name: Deploy

# Define quando o fluxo de trabalho será executado.
on:
  push:
    branches:
      - main
  workflow_dispatch:

# O trabalho que será executado.
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código do repositório.
      - name: Checkout do Código
        uses: actions/checkout@v4

      # Passo 2: Configuração de variáveis de ambiente.
      - name: Configurar Chave SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          
      # Passo 3: Adicionar a chave do host do servidor ao 'known_hosts'.
      # Isso garante que a conexão SSH seja segura.
      - name: Configurar Known Hosts
        run: |
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Passo 4: Conexão SSH e execução dos comandos.
      - name: Conectar e Fazer Deploy
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          VPS_PATH: ${{ secrets.VPS_PATH }}
        run: |
          ssh ${SSH_USER}@${SSH_HOST} "cd ${VPS_PATH} && git pull && npm install && npm run build"